# Generated by Django 3.1 on 2020-08-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='date_created',
            field=models.DateTimeField(default='2020 08 25'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateTimeField(default='2020 08 25'),
        ),
    ]
