# Generated by Django 2.2.3 on 2020-08-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20200825_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='date_created',
            field=models.DateTimeField(default='2020 08 26'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateTimeField(default='2020 08 26'),
        ),
    ]
